# wrangler.toml 配置文件
name = "prompt-peek-gallery"

# 基本配置
[site]
bucket = "./dist"
pages_build_output_dir = "dist"

# 构建命令
[build]
command = "npm run build:cloudflare"

# Worker配置
[build.upload]
dir = "dist"
main = "./_worker.js"
format = "modules"

# MIME类型规则
[[rules]]
type = "mime"
globs = ["*.js", "assets/*.js"]
content_type = "application/javascript"

[[rules]]
type = "mime"
globs = ["*.css"]
content_type = "text/css"

[[rules]]
type = "mime"
globs = ["site.webmanifest"]
content_type = "application/manifest+json"

# SPA路由
[[redirects]]
source = "/*"
destination = "/index.html"
status = 200 