// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmycbnojkxzquxybqgaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndteWNibm9qa3h6cXV4eWJxZ2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzU2ODgsImV4cCI6MjA2NTMxMTY4OH0.fo5XltKgPXnIkKNuE6JmUCMT0CIISX_Y0jqYx56L2Ts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);